"""
构建辅助脚本：从 D:\\AIkey\\SECURITY_KEY.dat 读取密钥，
生成 _secret.py 模块（base64 编码），供 PyInstaller 打包进 exe。
"""
import base64
import sys

SRC = r"D:\AIkey\SECURITY_KEY.dat"
DST = "_secret.py"

def main():
    try:
        with open(SRC, "rb") as f:
            raw = f.read()
    except FileNotFoundError:
        print(f"[ERROR] 密钥文件未找到: {SRC}")
        sys.exit(1)

    encoded = base64.b64encode(raw).decode("ascii")

    content = f"""# Auto-generated by build_embed_key.py — DO NOT EDIT
EMBEDDED_KEY = base64.b64decode({encoded!r})
"""

    # Don't import base64 at module level — avoid unnecessary dependency
    content = (
        "import base64\n\n"
        f"EMBEDDED_KEY = base64.b64decode({encoded!r})\n"
    )

    with open(DST, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[OK] {DST} 已生成 ({len(raw)} 字节 → {len(content)} 字符)")


if __name__ == "__main__":
    main()
