# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller build spec — onefile mode.
Packages everything into a single WeChatOA.exe.
Chromium browser is bundled externally via post_build.bat.
"""
import os
import sys
from pathlib import Path

PROJECT_DIR = Path(os.path.abspath(os.getcwd()))

block_cipher = None

a = Analysis(
    ["run.py"],
    pathex=[str(PROJECT_DIR)],
    binaries=[],
    datas=[
        (str(PROJECT_DIR / "app" / "templates"), "app/templates"),
        (str(PROJECT_DIR / "static"), "static"),
        (str(PROJECT_DIR / "data" / "fonts"), "data/fonts"),
        (str(PROJECT_DIR / "qrcode.jpg"), "."),
        (str(PROJECT_DIR / "头像.png"), "."),
        (str(PROJECT_DIR / ".env"), "."),
    ],
    hiddenimports=[
        "_secret",
        "starlette.middleware.cors",
        "starlette.middleware.trustedhost",
        "starlette.middleware.gzip",
        "starlette.middleware.httpsredirect",
        "uvicorn.logging",
        "uvicorn.loops.auto",
        "uvicorn.loops.asyncio",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.middleware.wsgi",
        "uvicorn.middleware.proxy_headers",
        "sqlalchemy.ext.asyncio",
        "sqlalchemy.ext.asyncio.base",
        "sqlalchemy.ext.asyncio.session",
        "sqlalchemy.ext.asyncio.engine",
        "sqlalchemy.ext.asyncio.result",
        "sqlalchemy.dialects.sqlite",
        "sqlalchemy.dialects.sqlite.aiosqlite",
        "aiosqlite",
        "apscheduler.triggers.cron",
        "apscheduler.triggers.interval",
        "apscheduler.executors.asyncio",
        "apscheduler.executors.pool",
        "apscheduler.jobstores.sqlalchemy",
        "apscheduler.jobstores.memory",
        "apscheduler.schedulers.asyncio",
        "httpx",
        "httpx._transports.default",
        "multipart",
        "cachelib",
        "cachelib.file",
        "app.sources.html_scraper",
        "app.sources.weibo_hot",
        "app.sources.v2ex_hot",
        "app.sources.zhihu_daily",
        "app.sources.juejin_hot",
        "app.sources.kr36",
        "app.sources.baidu_hot",
        "wechatsogou",
        "wechatsogou.filecache",
        "wechatsogou.request",
        "PIL.Image",
        "PIL.ImageDraw",
        "PIL.ImageFont",
        "PIL.ImageFilter",
        "PIL.ImageOps",
        "PIL._imaging",
        "playwright.async_api",
        "playwright.sync_api",
        "playwright._impl._async_base",
        "playwright._impl._sync_base",
        "playwright._impl._driver",
        "playwright._impl._connection",
        "playwright._impl._playwright",
        "playwright._impl._browser",
        "playwright._impl._browser_context",
        "playwright._impl._page",
        "playwright._impl._frame",
        "playwright._impl._network",
        "pydantic",
        "pydantic_settings",
        "pydantic_core",
        "yaml",
        "json",
        "asyncio",
        "concurrent",
        "concurrent.futures",
        "zoneinfo",
        "email",
        "email.mime",
        "email.mime.multipart",
        "email.mime.text",
        "email.mime.base",
    ],
    hookspath=[],
    hooksconfig={},
    excludes=[
        # GUI frameworks (not needed)
        "tkinter",
        "PyQt5",
        "PySide",
        "wx",
        "PyQt6",
        "PySide6",
        # Test modules
        "unittest",
        "unittest.mock",
        "pytest",
        "test",
        # Not needed
        "curses",
        "lib2to3",
        "nis",
        "ossaudiodev",
        "readline",
        "sphinx",
        "turtle",
        "turtledemo",
        "werkzeug.debug",
        "werkzeug.testapp",
        "setuptools._distutils",
        "packaging._manylinux",
        "wsproto",
        # Heavy ML / data science (not used by this project)
        "tensorflow",
        "torch",
        "torchvision",
        "torchaudio",
        "scipy",
        "scipy.special",
        "scipy.linalg",
        "scipy.spatial",
        "scipy.stats",
        "scipy.signal",
        "scipy.optimize",
        "scipy.integrate",
        "scipy.interpolate",
        "scipy.io",
        "scipy.sparse",
        "scipy.fft",
        "scipy.fftpack",
        "scipy.misc",
        "scipy.odr",
        "scipy.cluster",
        "pandas",
        "pandas.io",
        "pandas.plotting",
        "matplotlib",
        "matplotlib.backends",
        "matplotlib.pyplot",
        "PIL.ImageQt",
        "numba",
        "llvmlite",
        "bokeh",
        "plotly",
        "sympy",
        "statsmodels",
        "scikit_learn",
        "sklearn",
        "xgboost",
        "lightgbm",
        "triton",
        "pyarrow",
        "tables",
        "h5py",
        "opencv_python",
        "cv2",
        # Database drivers (not needed)
        "psycopg2",
        "MySQLdb",
        "pymysql",
        "asyncpg",
        "oracledb",
        # Cloud SDKs (not needed)
        "boto3",
        "botocore",
        "google.cloud",
        "azure",
        # Other unnecessary
        "gevent",
        "zope.interface",
        "IPython",
        "jedi",
        "parso",
        "pygments",
        "ipykernel",
        "jupyter",
        "fsspec",
        "openpyxl",
        "openpyxl.writer",
        # GIS
        "fiona",
        "shapely",
        "geopandas",
        "rasterio",
        "GDAL",
    ],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="WeChatOA",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
